# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeRefresher' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HomeRefresher
  pod 'Firebase/Core'

end

target 'HomeRefresher-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HomeRefresher-tvOS

  target 'HomeRefresher-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
